export const facts = [
  "A crocodile cannot stick its tongue out.",
  "A group of alligators is called a congregation.",
  "A group of badgers is called a cete.",
  "A group of bears is called a sleuth or sloth.",
  "A group of cobras is called a quiver.",
  "A group of crows is called a murder.",
  "A group of doves is called a flight or piteousness.",
  "A group of eagles is called a convocation.",
  "A group of ferrets is called a business.",
  "A group of flamingos is called a flamboyance.",
  "A group of foxes is called a skulk or leash.",
  "A group of geese is called a gaggle.",
  "A group of giraffes is called a tower.",
  "A group of goats is called a tribe or herd.",
  "A group of gorillas is called a band.",
  "A group of hawks is called a cast.",
  "A group of hedgehogs is called an array.",
  "A group of hippos is called a bloat.",
  "A group of hummingbirds is called a charm.",
  "A group of hyenas is called a cackle.",
  "A group of jaguars is called a shadow.",
  "A group of jellyfish is called a smack.",
  "A group of kangaroos is called a mob.",
  "A group of leopards is called a leap.",
  "A group of lions is called a pride.",
  "A group of moles is called a labor.",
  "A group of monkeys is called a troop or barrel.",
  "A group of mules is called a barren.",
  "A group of nightingales is called a watch.",
  "A group of otters is called a romp or raft.",
  "A group of owls is called a parliament.",
  "A group of parrots is called a pandemonium.",
  "A group of peacocks is called an ostentation.",
  "A group of pelicans is called a pod or scoop.",
  "A group of penguins is called a colony or rookery.",
  "A group of pigeons is called a flock or kit.",
  "A group of pigs is called a sounder.",
  "A group of pugs is called a grumble.",
  "A group of rabbits is called a colony or nest.",
  "A group of rats is called a mischief.",
  "A group of ravens is called an unkindness.",
  "A group of rhinos is called a crash.",
  "A group of seals is called a colony or herd.",
  "A group of sharks is called a shiver.",
  "A group of sheep is called a flock or drove.",
  "A group of snakes is called a den or pit.",
  "A group of squirrels is called a dray or scurry.",
  "A group of swans is called a bevy or wedge.",
  "A group of tigers is called an ambush or streak.",
  "A group of turkeys is called a rafter or gang.",
  "A group of turtles is called a bale or dole.",
  "A group of weasels is called a colony or gang.",
  "A group of whales is called a pod or gam.",
  "A group of wolves is called a pack.",
  "A group of zebras is called a dazzle.",
  "A jiffy is an actual unit of time: 1/100th of a second.",
  "A polar bear's skin is black.",
  "A shrimp's heart is in its head.",
  "A single cloud can weigh over 1 million pounds.",
  "Bananas are berries, but strawberries aren't.",
  "Butterflies taste with their feet.",
  "Cleopatra was not Egyptian, she was Greek.",
  "Honey never spoils.",
  "It is impossible for most people to lick their own elbow.",
  "Octopuses have three hearts.",
  "Starfish don't have brains.",
  "The Eiffel Tower can be 15 cm taller during the summer, due to thermal expansion.",
  "The Great Wall of China is not visible from space with the naked eye.",
  "The average cloud weighs around 1.1 million pounds.",
  "The average human brain weighs about 3 pounds.",
  "The average person blinks 15-20 times per minute.",
  "The average person spends 6 months of their life on the phone.",
  "The average person spends 6 months of their life waiting for red lights to turn green.",
  "The average person will eat 60,000 pounds of food in their lifetime.",
  "The average person will have 100,000 hairs on their head.",
  "The average person will produce 25,000 quarts of saliva in their lifetime.",
  "The average person will spend 1 year of their life commuting.",
  "The average person will spend 1 year of their life deciding what to wear.",
  "The average person will spend 1 year of their life exercising.",
  "The average person will spend 1 year of their life reading books.",
  "Russia is the largest country in the world by land area, covering over 17 million square kilometers.",
  "The Vatican City is the smallest country in the world, both in area and population.",
  "Mount Everest, the world's highest peak, grows by about 4 millimeters every year.",
  "The Sahara Desert is the largest hot desert in the world, almost as large as the United States.",
  "Canada has the longest coastline in the world, stretching over 243,042 kilometers.",
  "The Dead Sea, bordering Jordan and Israel, is the lowest point on Earth's land surface.",
  "Lake Baikal in Siberia, Russia, is the deepest and oldest freshwater lake in the world.",
  "The Amazon River is the largest river by discharge volume of water in the world.",
  "Australia is the only continent that is also a country.",
  "The country with the most islands is Sweden, with over 220,000 islands.",
  "The driest place on Earth is the Atacama Desert in Chile.",
  "The country with the most time zones is France, due to its overseas territories.",
  "Tokyo, Japan, is the most populous city in the world.",
  "The Great Barrier Reef, off the coast of Queensland, Australia, is the world's largest coral reef system.",
  "The highest uninterrupted waterfall in the world is Angel Falls in Venezuela.",
  "China shares its border with 14 different countries, more than any other country.",
  "The country with the most lakes is Canada, with over 3 million lakes.",
  "The coldest inhabited place on Earth is Oymyakon, Russia.",
  "The longest mountain range in the world is the Andes, running through seven South American countries.",
  "The country with the most volcanoes is Indonesia, with over 130 active volcanoes.",
  "The deepest ocean trench is the Mariana Trench in the Pacific Ocean.",
  "The country with the most pyramids is Sudan, not Egypt.",
  "The largest artificial island in the world is Flevopolder in the Netherlands.",
  "The country with the most castles is Germany.",
  "The largest cave system in the world is Mammoth Cave National Park in Kentucky, USA.",
  "The country with the most Nobel laureates is the United States.",
  "The largest hot spring in the world is Frying Pan Lake in New Zealand.",
  "The country with the most official languages is Bolivia, with 37 official languages.",
  "The largest single rock in the world is Mount Augustus in Western Australia.",
  "The country with the most sheep per capita is New Zealand.",
  "The country with the most natural arches is the United States, primarily in Utah.",
  "The longest road in the world is the Pan-American Highway, stretching from Alaska to Argentina.",
  "The country with the most UNESCO World Heritage Sites is Italy.",
  "The highest capital city in the world is La Paz, Bolivia.",
  "The country with the most rivers is Bangladesh.",
  "The largest delta in the world is the Ganges Delta, located in Bangladesh and India.",
  "The country with the most active geysers is Iceland.",
  "The largest freshwater island in the world is Manitoulin Island in Lake Huron, Canada.",
  "The country with the most time zones is Russia, with 11 time zones.",
  "The largest city in the world by area is New York City, USA.",
  "The country with the most glaciers is Chile.",
  "The largest waterfall by width is Khone Phapheng Falls in Laos.",
  "The country with the most deserts is China.",
  "The largest peninsula in the world is the Arabian Peninsula.",
  "The country with the most lakes is Finland, known as the 'Land of a Thousand Lakes'.",
  "The largest island in the world is Greenland.",
  "The country with the most coastline is Norway.",
  "The largest plateau in the world is the Tibetan Plateau.",
  "The country with the most national parks is the United States.",
  "The largest rainforest in the world is the Amazon Rainforest.",
  "The country with the most land borders is China.",
  "The largest ocean current is the Antarctic Circumpolar Current.",
  "The country with the most islands is Indonesia.",
  "The largest canyon in the world is the Yarlung Tsangpo Grand Canyon in Tibet.",
  "The country with the most active volcanoes is Japan.",
  "The largest hot desert in the world is the Sahara Desert.",
  "The country with the most UNESCO World Heritage Sites is China.",
  "The largest cold desert in the world is the Arctic Polar Desert.",
  "The country with the most official languages is India.",
  "The largest freshwater lake by surface area is Lake Superior.",
  "The country with the most sheep is China.",
  "The largest artificial lake in the world is Lake Kariba.",
  "The country with the most castles is France.",
  "The largest cave in the world is Son Doong Cave in Vietnam.",
  "The largest hot spring in the world is Grand Prismatic Spring in Yellowstone National Park.",
  "The country with the most official languages is South Africa.",
  "The largest single rock in the world is Uluru (Ayers Rock) in Australia.",
  "The country with the most sheep per capita is Australia.",
  "The average person will spend 1.5 years of their life eating.",
  "The average person will spend 10 years of their life watching movies.",
  "The average person will spend 2 years of their life looking at their phone.",
  "The average person will spend 2 years of their life shopping.",
  "The average person will spend 25 years of their life asleep.",
  "The average person will spend 3 years of their life cooking.",
  "The average person will spend 3 years of their life on vacation.",
  "The average person will spend 4 years of their life cleaning.",
  "The average person will spend 5 years of their life on social media.",
  "The average person will spend 6 months of their life brushing their teeth.",
  "The average person will spend 6 months of their life doing laundry.",
  "The average person will spend 6 months of their life waiting in line.",
  "The average person will spend 8 years of their life watching TV.",
  "The average person walks the equivalent of three times around the world in their lifetime.",
  "The dot over the letter 'i' is called a tittle.",
  "The first person to be charged with speeding was going 8 mph.",
  "The human body contains enough fat to make seven bars of soap.",
  "The human body has 1 brain.",
  "The human body has 1 heart.",
  "The human body has 10 times more bacterial cells than human cells.",
  "The human body has 100 trillion cells.",
  "The human body has 12 pairs of cranial nerves.",
  "The human body has 2 kidneys.",
  "The human body has 2 lungs.",
  "The human body has 2.5 million sweat glands.",
  "The human body has 206 bones.",
  "The human body has 23 pairs of chromosomes.",
  "The human body has 3 types of muscle tissue.",
  "The human body has 37 trillion cells.",
  "The human body has 4 main blood types.",
  "The human body has 5 liters of blood.",
  "The human body has 5 senses.",
  "The human body has 60,000 miles of blood vessels.",
  "The human body has 600 muscles.",
  "The human body has 7 major chakras.",
  "The human body has 78 organs.",
  "The human body has 9 major organ systems.",
  "The human brain generates about 20 watts of electrical power when awake.",
  "The human brain is 60% fat.",
  "The human eye can distinguish about 10 million different colors.",
  "The human heart beats about 100,000 times a day.",
  "The human nose can remember 50,000 different scents.",
  "The inventor of the Pringles can is buried in one.",
  "The inventor of the frisbee was turned into a frisbee after he died.",
  "The longest English word is 189,819 letters long and it's the chemical name for titin.",
  "The longest recorded flight of a chicken is 13 seconds.",
  "The longest word in the English language without a vowel is 'rhythm'.",
  "The national animal of Scotland is the unicorn.",
  "The only continent with no active volcanoes is Australia.",
  "The only food that doesn't spoil is honey.",
  "The only letter that doesn't appear in the name of any U.S. state is Q.",
  "The shortest commercial flight in the world lasts 57 seconds.",
  "The shortest complete sentence in the English language is 'I am.'.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
  "The strongest muscle in the body is the masseter (jaw muscle).",
  "The total weight of all ants on Earth is roughly equal to the total weight of all humans.",
  "The world's largest active volcano is Mauna Loa.",
  "The world's largest bird is the common ostrich.",
  "The world's largest bird of prey is the Andean condor.",
  "The world's largest canyon is the Grand Canyon.",
  "The world's largest desert is Antarctica.",
  "The world's largest fish is the whale shark.",
  "The world's largest flower is the Rafflesia arnoldii.",
  "The world's largest insect is the Goliath beetle.",
  "The world's largest land animal is the African bush elephant.",
  "The world's largest land carnivore is the polar bear.",
  "The world's largest land mammal is the African elephant.",
  "The world's largest living organism is a fungus in Oregon.",
  "The world's largest living structure is the Great Barrier Reef.",
  "The world's largest ocean is the Pacific Ocean.",
  "The world's largest reptile is the saltwater crocodile.",
  "The world's largest rodent is the capybara.",
  "The world's largest snake is the green anaconda.",
  "The world's largest spider is the Goliath birdeater.",
  "The world's largest waterfall is Angel Falls.",
  "The world's longest river is the Nile River.",
  "The world's oldest piece of chewing gum is 9,000 years old.",
  "The world's quietest room is at Microsoft's headquarters in Washington state.",
];